### ISSUE TITLE
Dumb 1.1 x64 pour Windows?

### ISSUE THREAD

**Issue by yellow-panther** [abulmo/Dumb#1]
Malheureusement je ne suis pas un programmeur des échecs; pourrais-tu créer un fichier binaire (Windows.exe) de v1.1 x64 (sans l´option bmi2, mais avec POPCNT, AVX, SSE4.2) sur la page https://github.com/abulmo/Dumb/releases , s´il te plaît?

:

**Comment by abulmo** [comment]
Fait:
https://github.com/abulmo/Dumb/releases/download/v1.1/dumb-windows.zip
Le zip contient un executable pour win64 (avec popcnt, avx, sse4.2) et un autre pour win32 (sans options).
