### ISSUE TITLE
Dumb v1.9 makes illegal move

### ISSUE THREAD

**Issue by tissatussa** [abulmo/Dumb#10]
in CuteChess :

![dumb_illegal_move](https://user-images.githubusercontent.com/1109281/184605781-ee866ab9-6711-490c-8a00-59c04ee006f0.png)

this position was reached by using starting position rnbq1b1r/pppp1kpp/5n2/4p3/3PP3/8/PPP2PPP/RNBQK1NR b KQ - 0 4
i also tried v1.10 and this version seems to run fine in CuteChess, no illegal move yet .. but how to be sure it differs from 1.9 ?

[ i'm using Xubuntu 22.04 ]

**Comment by abulmo** [comment]
Thank you for reporting this bug.
Dumb was badly guessing it was playing a fisher random chess game (or chess960) and erroneously handle the castling move by white.
Version 1.11 should fix this.
