### ISSUE TITLE
v1.2 64-bit exec crashes

### ISSUE THREAD

**Issue by tpoppins** [abulmo/Dumb#2]
instantly with exception code 0xc000001d, fault offset 0x00000000000ad320, according to WER. Looks like it uses AVX (or higher) CPU instructions, which this Westmere Xeon X5670 doesn't support. A surprising development, seeing that all Amoeba versions I tested on it run without any trouble on this Win 7 x64 SP1 box.

Providing a POPCNT compile would greatly broaden Dumb' s target userbase.

Tirsa@CCRL

**Comment by dejlek** [comment]
So it builds good executable if it does not build with POPCNT?

**Comment by abulmo** [comment]
popcnt is used in non crucial part of the search code and a more generic compilation does probably not affect the performance by a measurable bias.
I will provide soon an executable without popcnt/avx for version 1.2 and a new version 1.3, with even more simple code and an enhanced strength & speed.

**Comment by tpoppins** [comment]
Thank you, Richard.
