### ISSUE TITLE
Dumb 1.5 pour Windows 64-bit (.exe-file)

### ISSUE THREAD

**Issue by yellow-panther** [abulmo/Dumb#5]
Salut Richard,

Dumb v1.5 contient seulement le code source , mais il manque encore un fichier exécutable pour Windows 64-bit (ordinateur ivy-bridge, 4 GB RAM, Intel Core i5 , 4 threads, MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, Intel 64, NX, VMX, AES, AVX) sans l´option bmi2 https://en.wikipedia.org/wiki/Bit_Manipulation_Instruction_Sets

Salutations

**Comment by abulmo** [comment]
Désolé de mon retard...

Je viens de mettre à jour la version 1.5 qui est plus puissante que la version initialement prévue. Des fichiers zip avec des exécutables pour Windows et Linux sont fournis.

Cordialement
