### ISSUE TITLE
Dumb 1.6 illegal move

### ISSUE THREAD

**Issue by rchastain** [abulmo/Dumb#7]
Hello! I am testing Dumb 1.6, with CuteChess Cli, in FRC mode. I have just seen a game ended by an illegal move. I didn't study the position. I just saw that the move occurs after a castling...
[dumb16-illegalmove-g7f6.zip](https://github.com/abulmo/Dumb/files/5761439/dumb16-illegalmove-g7f6.zip)

**Comment by abulmo** [comment]
Your PGN file is not usable, the moves (starting from 1.. Ne6) are all illegal.

**Comment by rchastain** [comment]
Je viens de regarder plus attentivement. Non, sauf erreur de ma part, les coups ne sont pas illégaux. Il est vrai qu'en chargeant la partie dans xboard (c'est peut-être ce que vous avez fait aussi), j'obtiens un message me disant que le premier coup est illégal : mais c'est parce que la position n'est pas chargée comme il faut. Si je la recharge en sélectionnant préalablement la variante "FRC", je peux visionner la partie sans problème.
Par contre je me demande bien d'où vient le problème du dernier coup. Je suspectais un problème relatif au roque, mais en visionnant la partie ce n'est pas évident.

**Comment by abulmo** [comment]
Ok, c'était un problème lié xboard. J'ai réussi à répéter le bug, je vais voir de plus près d'où ça peut venir.
Merci de me l'avoir signalé.

**Comment by rchastain** [comment]
Pas de quoi. Bon courage pour la recherche de l'erreur.

**Comment by abulmo** [comment]
OK trouvé et corrigé. Le code corrigé a été "poussé" sur le site. Je vais faire une publication d'une nouvelle version dans la soirée. Pour la petite histoire, il se mettait en mode chess960/FRC après avoir joué les coups de la partie. La correction a consisté à déplacer une ligne de code pour qu'il soit en mode chess960 avant. Ce bug ne se voyait que si les tours étaient dans les coins, comme aux échecs orthodoxes, c'est pourquoi je ne l'avait pas vu plus tôt.
