### ISSUE TITLE
Dumb v1.8 loses on time

### ISSUE THREAD

**Issue by tissatussa** [abulmo/Dumb#8]
playing in CuteChess, Dumb v1.8 (your Linux asset) loses on time :

![Dumb_v1-8_losesontime_cutechess](https://user-images.githubusercontent.com/1109281/156595473-6c1c28c2-e8b9-4891-a7b3-bd1d6dcfe322.png)

here's the log : [Dumb_v1-8_losesontime_cutechess.zip](https://github.com/abulmo/Dumb/files/8178945/Dumb_v1-8_losesontime_cutechess.zip)

it's a pitty .. Dumb was winning against another engine that suffered from this issue : Pawn, see https://github.com/ruicoelhopedro/pawn .. it happens just before the 40th move (= my setting : 8 min per 40 moves + 3 sec bonus) .. i guess your code needs just a little twist to solve this :-)

**Comment by abulmo** [comment]
Thank you for reporting that issue. It is already fixed on the development version on my computer.
I will push a new version that fixes this bug about time handling and that is slightly stronger than version 1.8 in a few hours.

**Comment by tissatussa** [comment]
i tried to compile v1.9 but it didn't work :

```
~/Compiled/Dumb/src$ make
make clean
make[1]: Entering directory '/home/roelof/Compiled/Dumb/src'
rm -f *.o *.profraw *.profdata *.lst *.gcda
make[1]: Leaving directory '/home/roelof/Compiled/Dumb/src'
ldc2 -O3 -release -boundscheck=off -singleobj -w -dw  -flto=full -mcpu=native -defaultlib=phobos2-ldc-lto,druntime-ldc-lto -preview=intpromote -fprofile-generate dumb.d util.d board.d eval.d move.d search.d
Error: The LLVMgold.so plugin (needed for LTO) was not found. You can specify its path with -flto-binary=<file>.
make: *** [Makefile:56: pgo] Error 1
```


so i added (in my case) `-flto-binary=/usr/lib/llvm-13/lib/LLVMgold.so`, but now i get two other errors :


```
~/Compiled/Dumb/src$ make
make clean
make[1]: Entering directory '/home/roelof/Compiled/Dumb/src'
rm -f *.o *.profraw *.profdata *.lst *.gcda
make[1]: Leaving directory '/home/roelof/Compiled/Dumb/src'
ldc2 -O3 -release -boundscheck=off -singleobj -w -dw -flto-binary=/usr/lib/llvm-13/lib/LLVMgold.so -flto=full -mcpu=native -defaultlib=phobos2-ldc-lto,druntime-ldc-lto -preview=intpromote -fprofile-generate dumb.d util.d board.d eval.d move.d search.d
/usr/bin/ld.gold: error: cannot find -lphobos2-ldc-lto-shared
/usr/bin/ld.gold: error: cannot find -ldruntime-ldc-lto-shared
[...]
```


i tried to solve this also, but i didn't succeed yet : my Synaptic does not show these modules.
now i'm using your released asset, but can you help me solve the errors ?
i'm on Xubuntu 21.10

**Comment by abulmo** [comment]
Just remove the "-defaultlib=phobos2-ldc-lto,druntime-ldc-lto" option in the makefile. They are special libraries optimized with lto (link-time-optimisation), but dumb will work without them. These libraries are provided by  the ldc2 team on their github release, but not all Linux distributions provide them.

**Comment by tissatussa** [comment]
thanks, i try soon and report about it.

i had a similar issue with the Aboeba engine, also in D : https://github.com/abulmo/amoeba/issues/16 .. in the meantime i'm on another Linux distro and here ldc2 etc. gives some troubles of a new kind, but i'm learning a lot while trying to solve such errors !

**Comment by tissatussa** [comment]
> Just remove the "-defaultlib=phobos2-ldc-lto,druntime-ldc-lto" option in the makefile

i did, but i still get errors :

```
roelof@roelof-HP-Elite-x2-1012-G2:~/Compiled$ git clone https://github.com/abulmo/Dumb.git
Cloning into 'Dumb'...
remote: Enumerating objects: 400, done.
remote: Counting objects: 100% (284/284), done.
remote: Compressing objects: 100% (165/165), done.
remote: Total 400 (delta 183), reused 210 (delta 119), pack-reused 116
Receiving objects: 100% (400/400), 98.83 KiB | 3.80 MiB/s, done.
Resolving deltas: 100% (249/249), done.
roelof@roelof-HP-Elite-x2-1012-G2:~/Compiled$ cd Dumb/src/
roelof@roelof-HP-Elite-x2-1012-G2:~/Compiled/Dumb/src$ make
make clean
make[1]: Entering directory '/home/roelof/Compiled/Dumb/src'
rm -f *.o *.profraw *.profdata *.lst *.gcda
make[1]: Leaving directory '/home/roelof/Compiled/Dumb/src'
ldc2 -O3 -release -boundscheck=off -singleobj -w -dw  -flto=full -mcpu=native -preview=intpromote -fprofile-generate dumb.d util.d board.d eval.d move.d search.d
Error: The LLVMgold.so plugin (needed for LTO) was not found. You can specify its path with -flto-binary=<file>.
make: *** [Makefile:56: pgo] Error 1
roelof@roelof-HP-Elite-x2-1012-G2:~/Compiled/Dumb/src$ make
make clean
make[1]: Entering directory '/home/roelof/Compiled/Dumb/src'
rm -f *.o *.profraw *.profdata *.lst *.gcda
make[1]: Leaving directory '/home/roelof/Compiled/Dumb/src'
ldc2 -O3 -release -boundscheck=off -singleobj -w -dw -flto-binary=/usr/lib/llvm-13/lib/LLVMgold.so -flto=full -mcpu=native -preview=intpromote -fprofile-generate dumb.d util.d board.d eval.d move.d search.d
/tmp/lto-llvm-1f3c77.o:ld-temp.o:function _Dmain: error: undefined reference to '__llvm_profile_instrument_target'
/tmp/lto-llvm-1f3c77.o:ld-temp.o:function _Dmain: error: undefined reference to '__llvm_profile_instrument_target'
/tmp/lto-llvm-1f3c77.o:ld-temp.o:function _D4dumb3Uci6__ctorMFZCQuQr: error: undefined reference to '__llvm_profile_instrument_target'
/tmp/lto-llvm-1f3c77.o:ld-temp.o:function _D3std6format__T10FormatSpecTaZQp__T17writeUpToNextSpecTSQCd5stdio4File17LockingTextWriterZQCdMFNlNfKQBtZb: error: undefined reference to '__llvm_profile_instrument_range'
/tmp/lto-llvm-1f3c77.o:ld-temp.o:function _D3std4conv__T8textImplTAyaTQeTaZQtFNaNbNfQsaZQw: error: undefined reference to '__llvm_profile_instrument_range'
/tmp/lto-llvm-1f3c77.o:ld-temp.o:function _D3std9exception__T7bailOutHTCQBc6format15FormatExceptionZQBnFNaNfAyamMAxaZv: error: undefined reference to '__llvm_profile_instrument_range'
/tmp/lto-llvm-1f3c77.o:ld-temp.o:function _D3std6format__T15formatValueImplTSQBh5stdio4File17LockingTextWriterTdTaZQCfFNfKQBudMKxSQDiQDh__T10FormatSpecTaZQpZv: error: undefined reference to '__llvm_profile_instrument_range'
/tmp/lto-llvm-1f3c77.o:ld-temp.o:function _D3std5array__T8AppenderTAyaZQo4Data9__xtoHashFNbNeKxSQCaQBz__TQBwTQBqZQCeQBrZm: error: undefined reference to '__llvm_profile_instrument_target'
collect2: error: ld returned 1 exit status
Error: /usr/bin/cc failed with status: 1
make: *** [Makefile:56: pgo] Error 1
```

**Comment by abulmo** [comment]
Your compiler does not support profile guided optimisation (or some files are missing). I do not use xubuntu myself so I have no idea what to install for a successful compilation. Personally, I use the compiler provided by the ldc2 team on their github site, I think it works better than the one provided by any linux distribution: [ldc2](https://github.com/ldc-developers/ldc/releases)

**Comment by tissatussa** [comment]
aha .. thanks. I had problems using LDC(2) in the near past .. i will look into this, i'm unfamilar with D.
