### ISSUE TITLE
Bestmove output with mate 0 breaks PGN tools and GUIs

### ISSUE THREAD

**Issue by rwbc** [abulmo/Dumb#9]
Dumb quite often outputs a bestmove with an eval of `mate 0`, which is translated by some GUIs as +310.00 and by others as 0.00.
This breaks a lot of PGN analysing/graph tools, because the continuuos eval flow gets bonkers.

See this thread with examples
http://talkchess.com/forum3/viewtopic.php?f=2&t=80263

```
<Dumb_19-64(4): info depth 24 score cp 28 nodes 78324011 time 42800 nps 1829999 pv f1d3 d5c4 d3c4 c8d7 f4c7 d8c8 c7g3 c5b6 c4d3 h7h6 c1b1 e6e5 d3e4 d7g4 h1f1 f6e4 c2e4 f7f5 e4c4 g8h7 c3d5 e7c5 c4c5 b6c5 f1e1 
<Dumb_19-64(4): info depth 25 score mate 0 nodes 138511863 time 74000 nps 1871774 pv 
<Dumb_19-64(4): bestmove f4g5
```

**Comment by abulmo** [comment]
Thank you for reporting the bug.
I hope version 1.10 correct it.
